In [0]:
from google.colab import drive

ROOT = "/content/drive/"
drive.mount(ROOT)

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
import os
os.chdir('drive/My Drive/Facial_expression')

In [0]:
%run Training.py

Training Step: 40319  | total loss: 0.47303 | time: 17.519s
| Adam | epoch: 140 | loss: 0.47303 - acc: 0.8309 -- iter: 28700/28709
Training Step: 40320  | total loss: 0.47936 | time: 18.584s
| Adam | epoch: 140 | loss: 0.47936 - acc: 0.8328 | val_loss: 1.08806 - val_acc: 0.6333 -- iter: 28709/28709
--
INFO:tensorflow:/content/drive/My Drive/Facial_expression/data/emotion_recognition-40320 is not in all_model_checkpoint_paths. Manually adding it.
[[234   6  55  30  63  17  62]
 [  6  34   5   2   2   1   6]
 [ 42   2 210  28  96  56  62]
 [ 16   0  19 735  23  23  79]
 [ 64   2  74  53 313  13 134]
 [  6   0  24  24   5 342  14]
 [ 35   1  35  46  74  11 405]]
              precision    recall  f1-score   support

       Angry       0.58      0.50      0.54       467
   Disgusted       0.76      0.61      0.67        56
     Fearful       0.50      0.42      0.46       496
       Happy       0.80      0.82      0.81       895
         Sad       0.54      0.48      0.51       653
   Surp

In [0]:
from __future__ import division, print_function, absolute_import
import tflearn
import speech_data
import tensorflow as tf

learning_rate = 0.0001
training_iters = 300000  # steps
batch_size = 64

width = 20  # mfcc features
height = 80  # (max) length of utterance
classes = 10  # digits

batch = word_batch = speech_data.mfcc_batch_generator(batch_size)
X, Y = next(batch)
trainX, trainY = X, Y
testX, testY = X, Y #overfit for now

# Network building
net = tflearn.input_data([None, width, height])
net = tflearn.lstm(net, 128, dropout=0.8)
net = tflearn.fully_connected(net, classes, activation='softmax')
net = tflearn.regression(net, optimizer='adam', learning_rate=learning_rate, loss='categorical_crossentropy')
# Training

### add this "fix" for tensorflow version errors
col = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)
for x in col:
    tf.add_to_collection(tf.GraphKeys.VARIABLES, x ) 


model = tflearn.DNN(net, tensorboard_verbose=0)
while 1: #training_iters
  model.fit(trainX, trainY, n_epoch=10, validation_set=(testX, testY), show_metric=True,
          batch_size=batch_size)
  _y=model.predict(X)
model.save("tflearn.lstm.model")
print (_y)
print (y)

Instructions for updating:
Colocations handled automatically by placer.


ModuleNotFoundError: ignored

In [0]:
%run training_v1.py

Train on 28709 samples, validate on 7178 samples
Epoch 1/100
28709/28709 [==============================] - 18s 633us/step - loss: 1.9282 - acc: 0.2827 - val_loss: 1.5428 - val_acc: 0.4177
Epoch 2/100
28709/28709 [==============================] - 16s 559us/step - loss: 1.6040 - acc: 0.3738 - val_loss: 1.4537 - val_acc: 0.4571
Epoch 3/100
28709/28709 [==============================] - 16s 562us/step - loss: 1.4953 - acc: 0.4172 - val_loss: 1.3564 - val_acc: 0.4781
Epoch 4/100
28709/28709 [==============================] - 16s 566us/step - loss: 1.4113 - acc: 0.4586 - val_loss: 1.3221 - val_acc: 0.4996
Epoch 5/100
28709/28709 [==============================] - 16s 565us/step - loss: 1.3325 - acc: 0.4948 - val_loss: 1.2966 - val_acc: 0.5082
Epoch 6/100
28709/28709 [==============================] - 16s 568us/step - loss: 1.2568 - acc: 0.5228 - val_loss: 1.2735 - val_acc: 0.5212
Epoch 7/100
28709/28709 [==============================] - 16s 570us/step - loss: 1.1984 - acc: 0.5463 - val_lo

KeyboardInterrupt: ignored

In [0]:
%run CNN_Multi_faces_Video.py


Using TensorFlow backend.


KeyboardInterrupt: ignored

In [0]:
%run CNN_Picture.py

(35887, 2304)
(35887,)
7
(28709, 48, 48, 1)
(7178, 48, 48, 1)
(28709, 7)
(7178, 7)
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


/content/drive/My Drive/facial_expression_prediction/training.py:51: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=7)`
  classifier.add(Dense(output_dim = num_class, activation = 'softmax'))


56 52 142 142


ValueError: ignored

In [0]:
%run predition.py

Using TensorFlow backend.


(35887, 2304)
(35887,)
7
(28709, 48, 48, 1)
(7178, 48, 48, 1)
(28709, 7)
(7178, 7)
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
['Anger', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']
[[0.1419867  0.14393544 0.14359125 0.14526726 0.14066213 0.14196806
  0.1425891 ]]
